# Generated by Django 3.0.5 on 2020-06-23 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='', max_length=2000)),
                ('description', models.CharField(default='', max_length=2000)),
                ('city', models.CharField(default='', max_length=100)),
                ('address', models.CharField(blank=True, default='', max_length=500)),
                ('phone_number', models.CharField(default='', max_length=16)),
                ('image', models.ImageField(blank=True, upload_to='profile_image')),
                ('membership_fee', models.PositiveIntegerField(blank=True, null=True)),
                ('user_role', models.CharField(choices=[('co-operative', 'CO-OPERATIVE'), ('ajo', 'AJO'), ('none', 'NONE')], default='none', max_length=30)),
                ('user_status', models.CharField(choices=[('not verified', 'NOT VERIFIED'), ('pending verification', 'PENDING VERIFICIATION'), ('verified', 'VERIFIED')], default='not verified', max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='RequestCopAdminverification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RequestAjoAdminverification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=5000)),
                ('project_description', models.CharField(max_length=200)),
                ('project_contribution', models.CharField(choices=[('weekly', 'WEEKLY'), ('monthly', 'MONTHLY')], default='weekly', max_length=30)),
                ('project_distribution', models.CharField(choices=[('ascending', 'ASCENDING'), ('descending', 'DESCENDING'), ('random', 'RANDOM')], default='ascending', max_length=30)),
                ('project_duration', models.CharField(max_length=500)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
                ('project_returns', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectContributors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cooperapp.ProjectProfile')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CooperativeProjectProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=5000)),
                ('project_description', models.CharField(max_length=5000)),
                ('project_type', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('project_duration', models.CharField(default='', max_length=500)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
                ('project_returns', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CooperativeProjectContributors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'ACTIVE'), ('requesting out', 'REQUESTING OUT'), ('disabled', 'DISABLED')], default='disabled', max_length=30)),
                ('project_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cooperapp.CooperativeProjectProfile')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CooperativeContributions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(blank=True, null=True)),
                ('total_amount', models.PositiveIntegerField(blank=True, null=True)),
                ('date', models.DateField(auto_now=True)),
                ('project_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cooperapp.CooperativeProjectProfile')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contributions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(blank=True, null=True)),
                ('week_num', models.PositiveIntegerField(blank=True, null=True)),
                ('date', models.DateField(null=True)),
                ('project_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cooperapp.ProjectProfile')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
