# Generated by Django 3.0.5 on 2020-06-25 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperapp', '0002_auto_20200624_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cooperativecontributions',
            name='project_name',
        ),
        migrations.AddField(
            model_name='cooperativecontributions',
            name='cooperative_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cooperapp.UserProfile'),
        ),
    ]
