# Generated by Django 3.0.5 on 2020-06-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperapp', '0003_auto_20200625_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperativeprojectprofile',
            name='project_cost_perunitblock',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cooperativeprojectprofile',
            name='project_unitblock_available',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cooperativeprojectprofile',
            name='project_unitblock_purchased',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
