# Generated by Django 3.0.5 on 2020-06-25 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cooperapp', '0004_auto_20200625_0658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cooperativeprojectprofile',
            name='project_unitblock_purchased',
        ),
        migrations.CreateModel(
            name='CooperativeInvestment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unitblock_purchased', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'ACTIVE'), ('not active', 'NOT ACTIVE')], default='not active', max_length=30)),
                ('cooperative_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cooperapp.UserProfile')),
                ('investment_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cooperapp.CooperativeProjectProfile')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
