# Generated by Django 3.0.5 on 2020-07-02 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperapp', '0005_auto_20200625_0934'),
    ]

    operations = [
        migrations.CreateModel(
            name='CopInvite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiever_mail', models.CharField(max_length=5000)),
                ('cop_sender', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cooperapp.UserProfile')),
            ],
        ),
    ]
