# Generated by Django 3.0.5 on 2020-07-04 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperapp', '0006_copinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='copinvite',
            name='status',
            field=models.CharField(choices=[('on cooper', 'On Cooper'), ('not on cooper', 'NOT On Cooper')], default='not on cooper', max_length=30),
        ),
    ]
