# Generated by Django 3.0.8 on 2020-08-14 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperapp', '0008_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectprofile',
            name='contribution_amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
